# 앱 서버와 Nginx 로드밸런서의 접속 대상 및 그룹 정의
[app_servers]
sohyeon-app1 ansible_host=1.201.118.202
sohyeon-app2 ansible_host=1.201.118.10
sohyeon-app3 ansible_host=1.201.118.90

[load_balancer]
sohyeon-lb ansible_host=1.201.116.156